version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_DATABASE: node_dev_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./myconf/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
