version: "3.9"
services:
  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_HOST=db
  #     - DATABASE_USER=root
  #     - DATABASE_PASSWORD=password
  #     - DATABASE_NAME=synergeee_dev
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: synergeee_dev
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
